# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script: # use the default script which is equivalent to the following
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
   - julia -e 'Pkg.add("Ipopt"); Pkg.init(); Pkg.clone(pwd()); Pkg.build("Complementarity"); Pkg.test("Complementarity", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("Complementarity")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
